### ISSUE TITLE
Items feature

### ISSUE THREAD

**Issue by mlikr** [MuhdSaifulnizam15/tuition-management-system#10]
Change items to Kelas
Change units to Subjek

Table:
Nama
Subjek
Harga
Ditambah pada

Suggestion:
Add tutor details for each class.
Class schedule.
Attendance feature for each class (permission: tutor)

**Comment by MuhdSaifulnizam15** [comment]
Sengaja eh tmbh kerja waktu kerja, hahaha...  Sent from Mail for Windows 10 From: mlikrSent: Tuesday, 17 November, 2020 3:40 PMTo: MuhdSaifulnizam15/tuition-management-systemCc: SubscribedSubject: [MuhdSaifulnizam15/tuition-management-system] Items feature (#10) Change items to KelasChange units to SubjekTable:NamaSubjekHargaDitambah padaSuggestion:Add tutor details for each class.Class schedule.Attendance feature for each class (permission: tutor)—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by mlikr** [comment]
HEHEHEHEHEHEHEHEHEHEH SAYANG SAIFUL <3<3<3
